- hosts: localhost
  tasks:
  - name: Set up a task that will fail
    ansible.builtin.command: 'mkdir /home/ubuntu/failfolder'
    ignore_errors: True
  - name: create leonconfig
    become: True
    copy: 
      content: 'Leon spent too long on this'
      dest: /etc/leonconfig
      mode: '644'
    register: leontaskvar
    failed_when: leontaskvar.checksum != "e7c3116030da507ab80564f5e6c54ace62b3571e"
  - name: Print a message
    debug:
      msg: "Below is a variable"
  - name: Print the whole var
    debug:
      var: leontaskvar  # access like a dict
      verbosity: 1
  - name: Print a specific item from the car
    debug:
      var: leontaskvar.failed  # access like a dict
      verbosity: 1

