- hosts: ubuntu
  become: true
  vars:
  - nxingxvar: LEONINAVAR
  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: present
      update_cache: true


  - name: Copy nginx file over
    template:
      src: nginx.j2
      dest: /etc/nginx/nginx.conf
    register: nginx_config
#  - name: edit the file
#    command: "sed -i 's/nginx/{{ nxingxvar }}/' /etc/nginx/nginx.conf"
#    vars:
#    - nxingxvar: ASLDKJASLKA
  - name: Restart nginx if needed
    service:
      name: nginx
      state: restarted
  - name: Check that you can connect (GET) to a page and it returns a status 200    
    ansible.builtin.uri:
      url: http://localhost
      return_content: True
    register: webcontent
  - debug:
      var: webcontent.content