  # 'Play' level settings
    # 'Task' level settings
      # 'Module' level settings


- hosts: localhost  # can also be 'all' or '<groupname>'
  # become: True    # All tasks run as root
  tasks:
  - name: Install nginx with apt         # I like to name my tasks
    become: True                # This task will run as root
    ansible.builtin.apt:        # module name 
      # module arguments
      name: nginx
      state: present
  - name: Create the user dir
    ansible.builtin.file:
      path: /home/ubuntu/leonfolderfromaplaybook
      state: directory
  - name: Restart Nginx
    become: True                # This task will run as root
    ansible.builtin.systemd_service:
      name: nginx
      state: restarted